settings_version: 0.0.4
datasets_dir: E:\RT-DETR\datasets
weights_dir: E:\RT-DETR\RTDETRU\weights
runs_dir: E:\RT-DETR\RTDETRU\runs
uuid: 58248fbf74b840dfb76de1b9f67928eb1f9b7259a8ec171d6b17983b787b921b
sync: true
api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
